version: "{build}"
clone_depth: 1
clone_folder: c:\gopath\src\github.com\rhysd\vim-startuptime
environment:
    GOPATH: c:\gopath
install:
    - set PATH=C:\msys64\mingw64\bin;%PATH%
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - go get -v -t -d ./...
    - powershell -File .ci\install-vim.ps1
    - ps: |
        $Env:Path = $Env:Path + ';' + $Env:APPVEYOR_BUILD_FOLDER + '\nvim-win64\Neovim\bin\'
        $vim = $Env:APPVEYOR_BUILD_FOLDER + '\vim\'
        $Env:Path = $vim + (Get-ChildItem $vim).Name + ';' + $Env:Path
    - echo %Path%
    - vim --version
    - nvim --version
build: off
test_script:
    - go build
    - go test -v -race -coverprofile=coverage.txt
after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.txt"
deploy: off
