language: go
os:
  - linux
  - osx
install:
  - go get -t -d -v ./...
  - go version
  - go env
  - bash .ci/install-vim.sh
  - export PATH=$HOME/vim/bin:$HOME/nvim-${TRAVIS_OS_NAME}64/bin:$PATH
  - vim --version
  - nvim --version
script:
  - go build
  - go test -v -race -coverprofile=coverage.txt
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - /home/travis/vim
